# Now I am going to learn Tesorflow Fundamentals

# Introduction to Tensors

In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [3]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a Tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [7]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#Checking the Dimensions
vector.ndim

1

In [13]:
#Create a matrix (has more than 1 Dimensions)
matrix = tf.constant([[10,7,5],
                      [20,4,5]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  5],
       [20,  4,  5]], dtype=int32)>

In [14]:
matrix.ndim

2

In [17]:
another_matrix = tf.constant([[10.,2.,4,],
                              [3.,5.,9.],
                              [12.,4.,6.]],dtype=tf.float16) # sepecify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  2.,  4.],
       [ 3.,  5.,  9.],
       [12.,  4.,  6.]], dtype=float16)>

In [18]:
another_matrix.ndim

2

In [20]:
tensor = tf.constant([[[2,4,6],
                       [4,5,7]],
                      [[1,4,6],
                       [6,8,9]],
                      [[7,9,4],
                       [3,7,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[2, 4, 6],
        [4, 5, 7]],

       [[1, 4, 6],
        [6, 8, 9]],

       [[7, 9, 4],
        [3, 7, 7]]], dtype=int32)>

In [23]:
tensor.ndim

3

Learned so far

* Scalar: a single number
* vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array of numbers
