<a href="https://colab.research.google.com/github/girivj/LearningTensor/blob/main/tensorflow01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Now I am going to learn Tesorflow Fundamentals

# Introduction to Tensors

In [ ]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a Tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Checking the Dimensions
vector.ndim

1

In [ ]:
#Create a matrix (has more than 1 Dimensions)
matrix = tf.constant([[10,7,5],
                      [20,4,5]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  5],
       [20,  4,  5]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,2.,4,],
                              [3.,5.,9.],
                              [12.,4.,6.]],dtype=tf.float16) # sepecify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  2.,  4.],
       [ 3.,  5.,  9.],
       [12.,  4.,  6.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[2,4,6],
                       [4,5,7]],
                      [[1,4,6],
                       [6,8,9]],
                      [[7,9,4],
                       [3,7,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[2, 4, 6],
        [4, 5, 7]],

       [[1, 4, 6],
        [6, 8, 9]],

       [[7, 9, 4],
        [3, 7, 7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Learned so far

* Scalar: a single number
* vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array of numbers


### Creating tensors with `tf.Variable`

In [ ]:
# Creating the same tensor as seen in `tf.constant'
changeable_tensor = tf.Variable([20,10])
unchangeable_tensor = tf.constant([20,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 10], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in changeable_tensor
#changeable_tensor[0] = 10
#changeable_tensor

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(10)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Try this code
#unchangeable_tensor[0].assign(10)
#unchangeable_tensor

### Creating Random Tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
random_1 = tf.random.Generator.from_seed(10) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(10)
random_2 = random_2.normal(shape=(3,2))


#Are they Equal ?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Suffle the order of elements in a tensor

# Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled,seed = 42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [ ]:
#Creating a tensor of all ones
tf.ones([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Creating a tensor of all zeroes
tf.zeros(shape=(4,5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

## Numpy arrays into tensors

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A,shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
C = tf.constant(numpy_A,shape=(3,8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

## Getting information from tensors
 When you are dealing with tensors you probably want to know this attributes
* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Creating a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2,3,2,3))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 2, 3]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=36>)

In [ ]:
#Getting  various attributes fo tensor
print("Datatype of every element ",rank_4_tensor.dtype)
print("Number of Dimensios (rank) ",rank_4_tensor.ndim)
print("Shape of tensor ",rank_4_tensor.shape)
print("Elements along 0 axis ",rank_4_tensor.shape[0])
print("Elements along the last axis ",rank_4_tensor.shape[-1])
print("Total number of Elements in our tensor ",tf.size(rank_4_tensor).numpy())

Datatype of every element  <dtype: 'float32'>
Number of Dimensios (rank)  4
Shape of tensor  (2, 3, 2, 3)
Elements along 0 axis  2
Elements along the last axis  3
Total number of Elements in our tensor  36
